### ISSUE TITLE
Autocompletion for react-titanium

### ISSUE THREAD

**Issue by yuchi** [yomybaby/atom-titanium#11]
Would you be interested in porting the autocomplete functionality for JSX to make it work for [_react-titanium_](https://github.com/yuchi/react-titanium)? I’d be extremely helped by it personally and I’d love to offer such a feature.

**Comment by yomybaby** [comment]
Thanks for suggestion.

Already you know I'm very interested in react-titanium. But I'm not sure I can send a lot of time for react-titanium atom package.

When I start react things, I'll let you know. I would like to collaborate.

Anyway, I heard reactjs atom packages are quite good. `click to definition` functions of `atom-titanium` package runs on hyperclick package which by Facebook. 
In packages from Facebook,  there must be so many hints to provide autocompletion in JSX.
Let's digging and share :+1:

**Comment by yomybaby** [comment]
@yuchi , How are you doing? Today, I reviewed your yuchi/react-titanium repository. Is there any news? I'm just wondering about your plan with it.

**Comment by yuchi** [comment]
Honestly I had no time to invest in updating it. That's mostly because I have no knowledge of any production app using it.

Close this issue right away if you want. It is very plausible that I'll not touch react-titanium for a long time.

**Comment by yomybaby** [comment]
@yuchi  How are u doing? Now, do you develop with React or Ti?

I closed this issue. :)
