### ISSUE TITLE
Color TSS properties

### ISSUE THREAD

**Issue by m1ga** [yomybaby/atom-titanium#14]
It would be good to show the valid properties in another color:
![color](https://github-cloud.s3.amazonaws.com/assets/4334997/10565193/3f77cff6-75cb-11e5-86be-8d581bc33fd1.jpg)
e.g. keyword.other.tss

**Comment by yomybaby** [comment]
Thanks.

Previous version shows that. In the new version, tss grammar, there are several changes for auto-complete. It seem like an reason of missing.

I'll fix this.
