### ISSUE TITLE
i18n String property : preview and go-to-definition

### ISSUE THREAD

**Issue by yomybaby** [yomybaby/atom-titanium#24]
How about this feature? Very helpful or not?

**Comment by yuchi** [comment]
I have it in Liferay Portal Studio (an IDE for Java portals) and what I love the most is warning-highlighted **missing** strings.

**Comment by yomybaby** [comment]
@yuchi Yes, "warning-highlighted missing strings" is a good idea. thanks

**Comment by yomybaby** [comment]
New release 0.7.0 has a feature related i18n.
https://github.com/yomybaby/atom-titanium/releases/tag/v0.7.0
( not yet "warning-highlighted missing strings" )
