### ISSUE TITLE
Related files not opening on Windows 7

### ISSUE THREAD

**Issue by mcvendrell** [yomybaby/atom-titanium#32]
Hi.

I'm not able to open related files on a Windows 7 machine with CTRL+ALT+A/S/C/V.

No errors in console and Keybinding resolver is showing the right binds, so no clues. I thought that could be because Atoms was in C: and files was in W: but trying both in C: still doesn't work.

**Comment by yomybaby** [comment]
On ti-slack, you uploaded a below screenshot. What is the full path of `recaida_completa.js`? 
https://ti-slack.slack.com/files/mcvendrell/F11RVCY2V/pasted_image_at_2016_04_19_13_10.png

**Comment by mcvendrell** [comment]
The full path is controller\tabaquismo\recaida_completa.js but I also tried with root controllers like controller\index.js

**Comment by yomybaby** [comment]
I found a reason.
That is string concatantion to build a path. For cross-platform (windows, osx..), my pkg have to use path module for build path of related file.

https://github.com/yomybaby/atom-titanium/blob/master/lib/related.coffee#L19-L35

**Comment by yomybaby** [comment]
@mcvendrell I tried to fix this issue. But I'm not sure it work properly on Windows because I work with OSX. Please update package and let me know whether it work or not. 😄

**Comment by mcvendrell** [comment]
Ok, now the behaviour is other. I think you are close.
When pressing CTRL+ALT+V it opens a "non-existing" file *views.xml*
When pressing CTRL+ALT+C it opens a "non-existing" file *controller.js*
When pressing CTRL+ALT+S it opens a "non-existing" file *styles.tss*
When pressing CTRL+ALT+A nothing is opened.

So basically seems it is trying to open the corresponding folders but "lost" the right file.

**Comment by DouglasHennrich** [comment]
ctrl+option+ V/S/C are opening the files from the first project folder on the atom's tree

**Comment by yomybaby** [comment]
This pkg didn't support multi project on one Atom window. Because I open a single project every Atom window usually.

If change `getTiProjectRootPath` function, it will work property. @DouglasHennrich, if you have time, please make a PR :)

Check below code :
https://github.com/yomybaby/atom-titanium/blob/master/lib/ti-pkg-util.js#L31-L34

**Comment by DouglasHennrich** [comment]
on previous version, it worked fine oO

**Comment by yomybaby** [comment]
@DouglasHennrich I fixed the issue you mentioned.  Update to 0.9.7 and check result. :)

**Comment by DouglasHennrich** [comment]
@yomybaby Thanks dude! now it's working like a charm :D

**Comment by yomybaby** [comment]
@mcvendrell Update 0.9.8, and check result.
Now it work properly on Windows.

@mcvendrell @DouglasHennrich Thanks for reporting 👍

**Comment by mcvendrell** [comment]
Excellent, I will check next Monday when I have access to mi PC. Thank you!

**Comment by mcvendrell** [comment]
And... *YES* now it is working perfectly. You did it! :)
Thank you
