### ISSUE TITLE
Uncaught Error: app/app/assets/images does not exist.

### ISSUE THREAD

**Issue by m1ga** [yomybaby/atom-titanium#34]
I removed the whole auto-error message :)
The problem: I don't have /assets/images/ in my project and when I start typing in an image/backgroundImage property I get this error message:

### Stack Trace
Uncaught Error: /app/app/assets/images does not exist.
```
At .atom/packages/titanium-alloy/node_modules/find/index.js:194
```

Problem starts in 
https://github.com/yomybaby/atom-titanium/blob/master/lib/alloyCompletionRules.coffee#L63

Possible solution:
check for the /images/ folder first or start at /assets/

**Comment by yomybaby** [comment]
Thanks for reporting. v0.10.1 released :)

**Comment by m1ga** [comment]
:+1: thanks for the quick fix! Working fine, awesome feature again ;)
