### ISSUE TITLE
Uncaught BufferedProcessError: Failed to spawn command `alloy`. Make sure `alloy` is installed and on your PATH

### ISSUE THREAD

**Issue by wesvandervleuten** [yomybaby/atom-titanium#35]
/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262 Uncaught BufferedProcessError: Failed to spawn command `alloy`. Make sure `alloy` is installed and on your PATH

Mac OSX 10.11.4
Atom 1.7.3

**Comment by wesvandervleuten** [comment]
`sudo npm install -g alloy` fixed the problem. I used the newer appc command for building and stuff

**Comment by yomybaby** [comment]
Thanks you for letting us know how to fix it! :+1
