### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SummerWine93** [yomybaby/atom-titanium#36]
Hello. I really want to use this package but there is an issue so that I can't
I'm getting an error message: Failed to spawn command alloy. Make sure alloy is installed and on your PATH
on Mac. I'm trying to do anything with the package but I keep getting error messages. And I can't uninstall it to reinstall again

**Comment by yomybaby** [comment]
Please let me know about your environment. 
Version of Atom, alloy ...

**Comment by SummerWine93** [comment]
I dowloaded the latest versions of them today

**Comment by yomybaby** [comment]
Check this issue : https://github.com/yomybaby/atom-titanium/issues/35

**Comment by SummerWine93** [comment]
That you for your answer! =)
