### ISSUE TITLE
Failed to spawn command alloy. Make sure alloy is installed and on your PATH

### ISSUE THREAD

**Issue by developer82** [yomybaby/atom-titanium#37]
Right when starting Atom I get the following error message (it started after updating the package):

`Failed to spawn command alloy. Make sure alloy is installed and on your PATH`

I tried removing Atom completely (including all settings, packages) and downloaded everything again but still getting this.

When I open Atom it shows that error message and open chrom dev tools with the follwoing:

/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262 Uncaught BufferedProcessError: Failed to spawn command `alloy`. Make sure `alloy` is installed and on your PATH
/Users/ophir/.atom/packages/titanium-alloy/node_modules/atom-package-dependencies/index.js:53 hyperclick is already installed.
/Users/ophir/.atom/packages/titanium-build/node_modules/atom-package-dependencies/index.js:53 build is already installed.

**Comment by yomybaby** [comment]
Please try this. https://github.com/yomybaby/atom-titanium/issues/35
