### ISSUE TITLE
Open (all) related

### ISSUE THREAD

**Issue by m1ga** [yomybaby/atom-titanium#4]
hi,
could you add the crtl+alt+r shortcut too (similar to the old open-related package)? So it will open a split-vie with the other files?
https://github.com/soulglo/ti-alloy-related/issues/3

**Comment by yomybaby** [comment]
I love that feature. 
Let's make it more advanced. So I'd like to hear some additional idea. 

For example:

- close related files : (currently only open. After serveral opening, it bothers me.)
- Layout option : 3 cloumn or 2 column ..

Any good idea?

**Comment by m1ga** [comment]
sounds good! The more options the better :) I wasn't able to reuse an existing split so you could only run it once; after that it would split all views again. But I'm sure you find a way around that!

**Comment by yomybaby** [comment]
I just add this feature with reusing exist pane. But it's a little scratch. So I keep this issue as open. Welcome to any more advanced idea about this feature.

**Comment by m1ga** [comment]
nice, it's working great!
