### ISSUE TITLE
Customizing template for hyperclick code generating

### ISSUE THREAD

**Issue by yomybaby** [yomybaby/atom-titanium#44]
Recent @DouglasHennrich suggested this customizing feature. (#42 Thanks Douglas)

There are issue related with : https://discuss.atom.io/t/the-way-to-insert-next-line-n-into-config-string-type/29639

If anyone have an idea for this issue, please write comment on this issue.

**Comment by yomybaby** [comment]
Before adding text to editor, `\\n` should be replaced with `\n`.

**Comment by yomybaby** [comment]
https://discuss.atom.io/t/the-way-to-insert-next-line-n-into-config-string-type/29639/2?u=yomybaby

>The \n is just a convention that means "whatever is the line ending character(s) for the current platform". 
...
> The Settings View is doing the right thing, when you type \n turning it into "\\n" in the config.cson, that's the proper way to encode that value so that it comes back as \n when you view it in the Settings View again.

According to the above, I think that using `\n` on setting view is better. If you want to set in the config.cson, you should use `\\n` instead of pressing enter.

**Comment by DouglasHennrich** [comment]
I already tried to use on template input on setting view and its outputs `\\n`

**Comment by yomybaby** [comment]
What I want to say is `\\n` is expected result in config.json from `\n` setting view.
So I just want to keep this way.

Check this 2a9e03b commit.

After this commit :

On setting view, use `\n`
On config.json, use `\\n`
It works properly.

![settings_ __users_yomybaby_documents_tiworkspace_sandbox520ga](https://cloud.githubusercontent.com/assets/621215/15997331/a4310dbe-316d-11e6-8a4a-ce10140d0abc.png)
<img width="485" alt="index_tss_ __users_yomybaby_documents_tiworkspace_sandbox520ga" src="https://cloud.githubusercontent.com/assets/621215/15997339/bce926a2-316d-11e6-9437-965209752bbf.png">
<img width="205" alt="index_tss_ __users_yomybaby_documents_tiworkspace_sandbox520ga" src="https://cloud.githubusercontent.com/assets/621215/15997344/ca7fcffa-316d-11e6-856a-cd346fb7b6b5.png">

**Comment by yomybaby** [comment]
@DouglasHennrich 
After update to v0.11.2, you have to change your custom generationTemplate.
