### ISSUE TITLE
Auto completion from config.json (Alloy.CFG.*)

### ISSUE THREAD

**Issue by m1ga** [yomybaby/atom-titanium#45]
Typing and completing images is awesome. It would be a great addition to add `Alloy.CFG.*` (config.json) completion

http://docs.appcelerator.com/platform/latest/#!/api/Alloy-property-CFG

> {
>     "global": { "key": "defaultValue", "anotherKey": 12345 },
>     "env:development": {},
>     "env:test": {},
>     "env:production": {},
>     "os:ios": { "key": "iosValue" },
>     "os:android": { "key": "androidValue" },
>     "dependencies": {}
> }

Alloy.CFG.key;
Alloy.CFG.anotherKey;

**Comment by yomybaby** [comment]
It's a great idea. 👍 Thanks!

**Comment by yomybaby** [comment]
Please update new version. `Alloy.CFG.xxx` completion work on XML,JS,TSS.
Thanks for suggestion.

**Comment by yomybaby** [comment]
Opps. Just moment. I'll push more code about this. :(

**Comment by yomybaby** [comment]
Pleas, check v0.11.7 :)
