### ISSUE TITLE
Error if no File opended

### ISSUE THREAD

**Issue by jpolack** [yomybaby/atom-titanium#49]
Hello everyone,

if i press:
'ctrl-alt-v' or
'ctrl-alt-s' or
'ctrl-alt-c' or
'ctrl-alt-a'
with no file opended an Error occurres

Thank you in advance

Jonah

**Comment by yomybaby** [comment]
Thanks for reporting. I'll check this issue this weekend. 😆

**Comment by yomybaby** [comment]
@jpolack How about now?

**Comment by hansemannn** [comment]
@yomybaby Nope:
![screen shot 2016-11-07 at 21 20 41](https://cloud.githubusercontent.com/assets/10667698/20074322/1045f9de-a530-11e6-8abe-576fa8018771.png)

**Comment by yomybaby** [comment]
Now no error anymore with new release(v0.12.3).
Thank you.
