### ISSUE TITLE
open controller enhancement

### ISSUE THREAD

**Issue by gimdongwoo** [yomybaby/atom-titanium#5]
I think this.
code for createContoller method, hyperclick to controller.js

example)
```
Alloy.createController('photoViewer',params);
```
in this case, link for 'photoViewer' to open 'controllers/photoViewer.js'

**Comment by yomybaby** [comment]
:+1:
Great idea!!!
Additionally if the controller file doesn't exist, open confirm dialog which to make new controller.

**Comment by m1ga** [comment]
feel free to join my ti-create (https://github.com/m1ga/ti-create) package into yours! That would add the create part

**Comment by yomybaby** [comment]
@m1ga Great!!! Thanks

**Comment by yomybaby** [comment]
Now, you can add new `go to definition` pattern easily. 

- regExp is a regExp before the key text.
- targetPath : the function for path which will open.
- definitionRegExp : if you want to go to specific line, make this function. It return regular expression to find definition line. if there are several results, it will show select box automatically.

I'll write about how to add that with more detail soon.

See below code
https://github.com/yomybaby/atom-titanium/blob/master/lib/clickProvider.js#L54-L67
```
  js : [
    {
      regExp : /Alloy\.createController\(["']$/,
      targetPath : function(text,sourcePath){
        return sourcePath.replace(/app\/(.*)$/,`app/controllers/${text}.js`)
      }
    },
    {
      regExp : /Alloy\.Collections.instance\(["']$/,
      targetPath : function(text,sourcePath){
        return sourcePath.replace(/app\/(.*)$/,`app/models/${text}.js`)
      }
    }
  ]
```
