### ISSUE TITLE
Make sure Alloy is installed and on your path

### ISSUE THREAD

**Issue by AurelienHuet** [yomybaby/atom-titanium#50]
When I installed the "atom-titanium" i have this error in Atom :
/Users/aurelienhuet/Desktop/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:262 Uncaught BufferedProcessError: Failed to spawn command `alloy`. Make sure `alloy` is installed and on your PATH

<img width="1280" alt="capture d ecran 2016-08-07 a 22 16 56" src="https://cloud.githubusercontent.com/assets/8513265/17465076/7cab9a88-5ced-11e6-8ce0-373b1093ff65.png">

**Comment by yomybaby** [comment]
Thank you for reporting. 🍺
Did you try #35?

**Comment by jmcerrejon** [comment]
Same here. I tried the fix #35 but it doesn't work.

**Versions**

Atom: 1.9.6

npm: 3.7.2

node: 0.12.7

OSX: 10.10.5

**Comment by yomybaby** [comment]
I just fixed this issue. 
If you use Alloy 1.7.x or before, YOU SHOULD UNCHECK alloy version setting of this package.

![settings_ ___documents_tiworkspace_playce_ti-playce](https://cloud.githubusercontent.com/assets/621215/20460729/d9ab5f26-af30-11e6-91f2-de29c98fc7d7.jpg)

Please check new release.
