### ISSUE TITLE
Autocompletion outdated?

### ISSUE THREAD

**Issue by hansemannn** [yomybaby/atom-titanium#51]
Hey @yomybaby,

thanks for this great plugin again! Helps organizing a looot of files and projects every day 🚀 

So I noticed that some of the autocompletion hints are a bit outdated. Examples
- `Ti.UI.iOS.NavigationWindow` won't be suggested
- `Ti.UI.KEYBOARD_EMAIL` (deprecated) would be suggested, but `Ti.UI.KEYBOARD_TYPE_EMAIL` (replacement) won't
- Newer API's like `Ti.UI.iOS.PreviewContext` won't be suggested in any kind
Is there a jsca you are working with? Would be cool to have this updated, thx!

Hans

~~**EDIT**: Looking at [this line](https://github.com/yomybaby/atom-titanium/blob/master/completionGenerateScript/alloy.js#L4), it takes the API's from the Alloy-bundled jsca. So that one might be outdated.~~ That's only the Alloy one, and the [Titanium one](https://github.com/yomybaby/atom-titanium/blob/master/completionGenerateScript/titanium.js#L20) should be up to date.

**Comment by yomybaby** [comment]
Thanks for reporting!! I'll try to improve.

- Currently, NavigationWindow tag is suggested. Please check again
- Does Alloy support `<PreviewContext>` Tag?  Do you mean suggest on JS file?

**Comment by yomybaby** [comment]
v.0.13.x display deprecated or not.
It works only const value.

![index_xml_ ___documents_tiworkspace_sandbox](https://cloud.githubusercontent.com/assets/621215/20460633/47c547a6-af2c-11e6-904c-d31ff711d1b9.jpg)

**Comment by hansemannn** [comment]
Nice! 🚀
