### ISSUE TITLE
TextEditor.get is deprecated.

### ISSUE THREAD

**Issue by vsantana** [yomybaby/atom-titanium#54]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:101:14)
Object.getFileEditor (/Users/vsantana/.atom/packages/titanium-alloy/lib/ti-pkg-util.js:15:55)
findDefinition (/Users/vsantana/.atom/packages/titanium-alloy/lib/clickProvider.js:366:27)
<unknown> (/Users/vsantana/.atom/packages/titanium-alloy/lib/clickProvider.js:444:38)
Function._.each._.forEach (/Users/vsantana/.atom/packages/titanium-alloy/node_modules/underscore/underscore.js:153:9)
Object.getSuggestionForWord (/Users/vsantana/.atom/packages/titanium-alloy/lib/clickProvider.js:443:9)
```

**Comment by yomybaby** [comment]
Thanks for reporting! 👍 
I just removed dependency on `displayBuffer`.

**Comment by m1ga** [comment]
The message still shows up. https://github.com/yomybaby/atom-titanium/blob/master/lib/ti-pkg-util.js#L15 still has `displayBuffer`

**Comment by yomybaby** [comment]
@m1ga 
I removed that also. :)
