### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokens' of undefined

### ISSUE THREAD

**Issue by DouglasHennrich** [yomybaby/atom-titanium#55]
`.atom/packages/titanium-alloy/lib/viewProvider.coffee:344`

Atom version `1.13.0 x64`

**Comment by yomybaby** [comment]
Thanks for reporting. It related with #54 .
Please update package and check again. 😄

**Comment by yomybaby** [comment]
If you get same error, please reopen this issue. :)
