### ISSUE TITLE
Autocomplete controllers with `/` prefix

### ISSUE THREAD

**Issue by hansemannn** [yomybaby/atom-titanium#57]
Ti SDK introduced the full NodeJS require-spec. This also includes the recommendation to use `/` for all require-prefixes, including Alloy controllers. So when I create a new controller using `Alloy.createController('my/controller')`, it suggests the correct controller, great! But when using `Alloy.createController('/my/controller')`, it doesn't detect my autocomplete flow. It would be great if it could!

P.S.: The hyperlinking already works!

**Comment by yomybaby** [comment]
Great!
I'll check this soon.

**Comment by yomybaby** [comment]
Done!
If you type with `/` prefix, it works property.
if you type without `/` prefix, `/` prefix will be added when autocompleting.

This work on xml file (`<Require src='/my...`)

Check below gif :)
![with](https://user-images.githubusercontent.com/621215/27256747-ab3a15e4-53f2-11e7-954c-f6c80bf182fe.gif)

**Comment by hansemannn** [comment]
Beautiful :)
