### ISSUE TITLE
Support Classic Titanium Project ?

### ISSUE THREAD

**Issue by jacklkw** [yomybaby/atom-titanium#59]
Dear Jong Eun Lee ,

First Thank You for Create this Package this is so Cool . Code without Appcelerator Studio .

I have a Classic Titanium Project Build by Appcelerator Studio.  Is  **atom-titanium** support the Classic Titanium Project ? or i need to convert to Alloy Project ? 

If not support do you plan to add this in your list ?

**Comment by yomybaby** [comment]
Most of features of this package are dpends on Alloy. Only few feature such as i18n completion is not depends on Alloy. But I'm not sure it works properly. 

I recommend to use Alloy. It's so useful :)

**Comment by yomybaby** [comment]
And I have no plan to support classic project. Sorry about that.
