### ISSUE TITLE
Hyperclick for functions with blank space(s) before parenthesis

### ISSUE THREAD

**Issue by phobeous** [yomybaby/atom-titanium#64]
Some developers use to add a space char between function name and parenthesis:
function clickHandler (e){
   console.log(JSON.stringify(e));
}
Hyperclick doesn't detect the function. It would be nice if the regexp that detects functions declaration consider spaces and tabs before parenthesis.

**Comment by yomybaby** [comment]
Thanks for letting me know. I'll check this issue tonight or tommorow.
