### ISSUE TITLE
Optimize startup time

### ISSUE THREAD

**Issue by m1ga** [yomybaby/atom-titanium#65]
Not sure how or if it can be done but it would be nice to optimize the startup time:
![screenshot_20170528_115448](https://cloud.githubusercontent.com/assets/4334997/26527824/a565c3f4-439c-11e7-93d7-e1a130d682f2.png)

**Comment by yomybaby** [comment]
It might takena long time for loading json for API autocomple. I'll make it load a josn file when needs. 

Thank for all your comment!

**Comment by yomybaby** [comment]
Check new version(0.13.11).
It load completion file when pkg need it, but I'm not sure how much time is reduced.

**Comment by m1ga** [comment]
Nice, `267ms` (half the time it was before) now!

**Comment by yomybaby** [comment]
Ok. I close this issue but I'll keep on it.  
Thanks
