### ISSUE TITLE
The plugin doesn't work as expected on atom 1.17.1

### ISSUE THREAD

**Issue by malhajj** [yomybaby/atom-titanium#66]
After updating atom to 1.17.1, the tabs of alloy related files doesn't open as expected when using (open all)

**Comment by yomybaby** [comment]
Thanks for letting me know.
Atom API has changed. It might be related with new Panel API.
I tried to fix this issue but I couldn't.
If you know any package which has split layout function, please let me know.

**Comment by malhajj** [comment]
Hello,

I think you can benefit from **split diff** package, cause they had an update just after atom update and its working fine.

Thanks,

**Comment by gimdongwoo** [comment]
Right. `split diff` opens the panel well.

**Comment by gimdongwoo** [comment]
Maybe this will help you.
https://github.com/joshjensen/related-split-view

**Comment by yomybaby** [comment]
Thanks you!!
Tonight I'll try to fix it!

**Comment by yomybaby** [comment]
+1 feature : close duplicated editor when open all related files. cb5720db6caf9cbaf7ef69a153b09415dcad6454
😄

**Comment by gimdongwoo** [comment]
Hi.
Atom 1.17.2 does not work with `Open all relative files`.
