### ISSUE TITLE
Toggle show all related files with the same keyboard shortcut that shows them

### ISSUE THREAD

**Issue by malhajj** [yomybaby/atom-titanium#69]
It's better to toggle show all related files with **Ctrl+alt+a**, instead of pressing shift to close them, which request more than 4 fingers to be established.

Again, thanks for this great plugin, its the first one that I install on new atom installation.

**Comment by yomybaby** [comment]
Great idea:)
I'll be back tonight. 👍

**Comment by yomybaby** [comment]
@malhajj Thanks.
More detail on [release note](https://github.com/yomybaby/atom-titanium/releases/tag/v0.14.0)

**Comment by malhajj** [comment]
@yomybaby,
Thanks so mush for your direct implementation, it's so helpful.
