### ISSUE TITLE
Suggestions for supporting different source path.

### ISSUE THREAD

**Issue by gimdongwoo** [yomybaby/atom-titanium#70]
To use Babel transcoding, my sources are in /src/, not /app/.

Thus, many functions of atom-titanium are restricted.

I would like to be able to change the source path, through the settings of the package or the configuration file of the project root.

Thank you!!

**Comment by yomybaby** [comment]
Thanks for suggestion.
It's easy to make it but useful in your case.

Please check new version. :)

**Comment by gimdongwoo** [comment]
Quick fix, thank you very much!!
